#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/9cc27ed3-720b-4132-badf-c82b1b90e0a7/ # 
title: retail api
#Developed by Esayas k. 
#Project Manager: Henok 
#Craft Software, April 2020.

documentation:
  - !include documentation.raml
types:
  product: !include datatypes/product.raml
  bill: !include datatypes/bill.raml
  productCatagory: !include datatypes/productcatagory.raml
traits:
  call: !include calltraits.raml
resourceTypes: 
  calling1:
    usage: This API is used by <<resourcePathName>>
    description: API is used ti retrieve and create <<resourcePathName>>
    get:
      description: This API is  used to fetchs list of all  <<resourcePathName>> data
      responses: 
        200:
          body: 
            application/json:
              type: |
                <<exampleReference>>
              example: |
                <<exampleReference1>>
      is: [call]
    post:
      description: This API is used to create <<resourcePathName>>
      body: 
        application/json:
          example: |
            <<exampleReference2>>
      responses: 
        201:
          body: 
            application/json:
              example: |
                {"message":"<<resourcePathName>> Created"}
  calling2:
    get:
      description: This API is used to fetch  specific <<resourcePathName>> data
      queryParameters:
        id: 
          type: integer
          required: true
      responses: 
        200:
          body: 
            application/json:
              example: |
                <<exampleReference3>>
    put:
      description: This API is used to update specific <<resourcePathName>>
      queryParameters:
        id: 
          type: integer
          required: true
      body: 
        application/json:
          example: |
            <<exampleReference4>>
      responses: 
        200:
          body: 
            application/json:
              example: |
                {"message":"<<resourcePathName>> successfully updated"}
    delete:
      description: This API is used to delete specific <<resourcePathName>>
      queryParameters:
        id: 
          type: integer
          required: true      
      body: 
        application/json:
          example: |
            <<exampleReference5>>
      responses: 
        200:
          body: 
            application/json:
              example: |
                {"message":"<<resourcePathName>> successfully deleted"}
/Products:
  type:
    calling1:
      exampleReference: product []
      exampleReference1: !include example1/getallproduct.json
      exampleReference2: !include example1/postproduct.json
  /productid:
    type:
      calling2:
        exampleReference3: !include example1/getsingleproduct.json
        exampleReference4: !include example1/putproduct.json
        exampleReference5: !include example1/deleteproduct.json
/Bills:
  type:
    calling1:
      exampleReference: bill []
      exampleReference1: !include example2/getallbill.json
      exampleReference2: !include example2/postbill.json
  /billid:
    type:
      calling2:
        exampleReference3: !include example2/getsinglebill.json
        exampleReference4: !include example2/putbill.json
        exampleReference5: !include example2/deletebill.json
/Productcatagory:
  type:
    calling1:
      exampleReference: productCatagory []
      exampleReference1: !include example3/getallproductcatagory.json
      exampleReference2: !include example3/postproductcatagory.json
  /productcatagoryid:
    type:
      calling2:
        exampleReference3: !include example3/getsingleproductcatagory.json
        exampleReference4: !include example3/putproductcatagory.json
        exampleReference5: !include example3/deleteproductcatagory.json
